---
- name: Create MySQL namespace
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'namespace.yml.j2') | from_yaml }}"
    kubeconfig: /home/jazzfact/.kube/config

- name: Create MySQL secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'secret.yml.j2') | from_yaml }}"
    kubeconfig: /home/jazzfact/.kube/config

- name: Create MySQL PVC
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'pvc.yml.j2') | from_yaml }}"
    kubeconfig: /home/jazzfact/.kube/config

- name: Deploy MySQL
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'deployment.yml.j2') | from_yaml }}"
    kubeconfig: /home/jazzfact/.kube/config

- name: Create MySQL service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'service.yml.j2') | from_yaml }}"
    kubeconfig: /home/jazzfact/.kube/config

- name: Wait for MySQL to be ready
  kubernetes.core.k8s_info:
    kind: Deployment
    name: mysql
    namespace: "{{ mysql_namespace }}"
    kubeconfig: /home/jazzfact/.kube/config
  register: mysql_deployment
  until: >-
    mysql_deployment.resources[0].status.readyReplicas | default(0) == 1
  retries: 30
  delay: 10
