---
- name: k3s 설치 스크립트 실행
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: k3s.yaml 파일이 생성될 때까지 대기
  wait_for:
    path: /etc/rancher/k3s/k3s.yaml
    state: present
    timeout: 30

- name: 원래 일반 사용자 이름 가져오기
  command: whoami
  register: current_user
  become: false # sudo 권한을 끄고 원래 사용자로 실행하여 이름 획득
  changed_when: false

- name: 사용자 홈 디렉토리에 .kube 폴더 생성
  file:
    path: "/home/{{ current_user.stdout }}/.kube"
    state: directory
    mode: '0755'
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"

- name: k3s 설정 파일을 사용자 config로 복사
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ current_user.stdout }}/.kube/config"
    remote_src: yes
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: '0600'

- name: .bashrc에 KUBECONFIG 환경변수 추가
  lineinfile:
    path: "/home/{{ current_user.stdout }}/.bashrc"
    line: "export KUBECONFIG=/home/{{ current_user.stdout }}/.kube/config"
    state: present