apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: monitoring 
  labels:
    release: monitoring  
spec:
  namespaceSelector: 
    matchNames:
      - ktcloud7
  selector:
    matchLabels:
      app: backend   
  endpoints:
    - port: http
      path: /metrics